# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: futuracommon/protos/audioservice.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&futuracommon/protos/audioservice.proto\x12\x05\x61udio\"3\n\nAudioChunk\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x11\n\tclient_id\x18\x02 \x01(\t\"0\n\x0cStreamStatus\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2H\n\rAudioStreamer\x12\x37\n\x0bStreamAudio\x12\x11.audio.AudioChunk\x1a\x13.audio.StreamStatus(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'futuracommon.protos.audioservice_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_AUDIOCHUNK']._serialized_start=49
  _globals['_AUDIOCHUNK']._serialized_end=100
  _globals['_STREAMSTATUS']._serialized_start=102
  _globals['_STREAMSTATUS']._serialized_end=150
  _globals['_AUDIOSTREAMER']._serialized_start=152
  _globals['_AUDIOSTREAMER']._serialized_end=224
# @@protoc_insertion_point(module_scope)
