# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: futuracommon/protos/healthcheck.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%futuracommon/protos/healthcheck.proto\x12\x06health\" \n\rHealthRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\"\x9b\x01\n\x0eHealthResponse\x12\x34\n\x06status\x18\x01 \x01(\x0e\x32$.health.HealthResponse.ServiceStatus\x12\x17\n\x0f\x63urrent_backend\x18\x02 \x01(\t\":\n\rServiceStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SERVING\x10\x01\x12\x0f\n\x0bNOT_SERVING\x10\x02\x32G\n\rHealthService\x12\x36\n\x05\x43heck\x12\x15.health.HealthRequest\x1a\x16.health.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'futuracommon.protos.healthcheck_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHREQUEST']._serialized_start=49
  _globals['_HEALTHREQUEST']._serialized_end=81
  _globals['_HEALTHRESPONSE']._serialized_start=84
  _globals['_HEALTHRESPONSE']._serialized_end=239
  _globals['_HEALTHRESPONSE_SERVICESTATUS']._serialized_start=181
  _globals['_HEALTHRESPONSE_SERVICESTATUS']._serialized_end=239
  _globals['_HEALTHSERVICE']._serialized_start=241
  _globals['_HEALTHSERVICE']._serialized_end=312
# @@protoc_insertion_point(module_scope)
