# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from futuracommon.protos import tts_pb2 as futuracommon_dot_protos_dot_tts__pb2


class TextToSpeechStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessText = channel.unary_unary(
                '/tts.TextToSpeech/ProcessText',
                request_serializer=futuracommon_dot_protos_dot_tts__pb2.TextRequest.SerializeToString,
                response_deserializer=futuracommon_dot_protos_dot_tts__pb2.SessionResponse.FromString,
                )
        self.StreamAudio = channel.unary_stream(
                '/tts.TextToSpeech/StreamAudio',
                request_serializer=futuracommon_dot_protos_dot_tts__pb2.StreamRequest.SerializeToString,
                response_deserializer=futuracommon_dot_protos_dot_tts__pb2.AudioChunk.FromString,
                )


class TextToSpeechServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessText(self, request, context):
        """Receives text and returns a session ID for audio streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAudio(self, request, context):
        """Streams audio to the client using the session ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TextToSpeechServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessText': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessText,
                    request_deserializer=futuracommon_dot_protos_dot_tts__pb2.TextRequest.FromString,
                    response_serializer=futuracommon_dot_protos_dot_tts__pb2.SessionResponse.SerializeToString,
            ),
            'StreamAudio': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamAudio,
                    request_deserializer=futuracommon_dot_protos_dot_tts__pb2.StreamRequest.FromString,
                    response_serializer=futuracommon_dot_protos_dot_tts__pb2.AudioChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tts.TextToSpeech', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TextToSpeech(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tts.TextToSpeech/ProcessText',
            futuracommon_dot_protos_dot_tts__pb2.TextRequest.SerializeToString,
            futuracommon_dot_protos_dot_tts__pb2.SessionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/tts.TextToSpeech/StreamAudio',
            futuracommon_dot_protos_dot_tts__pb2.StreamRequest.SerializeToString,
            futuracommon_dot_protos_dot_tts__pb2.AudioChunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
