# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: futuracommon/protos/tts.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x66uturacommon/protos/tts.proto\x12\x03tts\"/\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\"%\n\x0fSessionResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t\"#\n\rStreamRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\"\x1a\n\nAudioChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32\x7f\n\x0cTextToSpeech\x12\x37\n\x0bProcessText\x12\x10.tts.TextRequest\x1a\x14.tts.SessionResponse\"\x00\x12\x36\n\x0bStreamAudio\x12\x12.tts.StreamRequest\x1a\x0f.tts.AudioChunk\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'futuracommon.protos.tts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEXTREQUEST']._serialized_start=38
  _globals['_TEXTREQUEST']._serialized_end=85
  _globals['_SESSIONRESPONSE']._serialized_start=87
  _globals['_SESSIONRESPONSE']._serialized_end=124
  _globals['_STREAMREQUEST']._serialized_start=126
  _globals['_STREAMREQUEST']._serialized_end=161
  _globals['_AUDIOCHUNK']._serialized_start=163
  _globals['_AUDIOCHUNK']._serialized_end=189
  _globals['_TEXTTOSPEECH']._serialized_start=191
  _globals['_TEXTTOSPEECH']._serialized_end=318
# @@protoc_insertion_point(module_scope)
